package com.zoran.leetcode.simple4;

import java.util.HashMap;
import java.util.Map;

/**
 * ÅÐ¶ÏÂ·Ïß³ÉÈ¦
 * https://leetcode-cn.com/submissions/detail/4928071/
 */
public class Test145 {
	public static void main(String[] args) {
		Test145 test145 = new Test145();
		String string = "RULDDLLDLRDUUUURULRURRRRLRULRLULLLRRULULDDRDLRULDRRULLU"
				+ "DDURDLRRUDRUDDURLLLUUDULRUDRLURRDRLLDDLLLDLRLLRUUDUURDRLDUDRUDRLUDULRL"
				+ "UDRLDDUULDDLDURULUDUUDDRRDUURRLRDLDLRLLDRRUUURDLULLURRRRDRRURDUURDLRRUUL"
				+ "RURRUULULUUDURUDLRDDDDDURRRLRUDRUULUUUULDURDRULLRRRUDDDUUULUURRDRDDRLLDRLD"
				+ "ULDLUUDRDLULLDLDDRUUUUDDRRRDLLLLURUURLRUUULRDDULUULUURDURDDDRRURLURDLLLRLULR"
				+ "DLDDLRDRRRRLUURRRRLDUDLLRUDLDRDLDRUULDRDULRULRRDLDLLLUDLDLULLDURUURRLLULUURL"
				+ "RLRDUDULLDURRUDDLDDLLUDURLLRLDLDUDLURLLDRRURRDUDLDUULDUDRRUDULLUUDURRRURLULDDL"
				+ "RRURULUURURRDULUULDDDUUDRLDDRLULDUDDLLLDLDURDLRLUURDDRLUDRLUDLRRLUUULLDUUDUDURRU"
				+ "ULLDDUDLURRDDLURLDRDRUDRLDDLDULDRULUDRRDRLLUURULURRRUDRLLUURULURRLUULRDDDRDDLDRLD"
				+ "RLDUDRLDRLDDLDUDDURUDUDDDLRRDLUUUDUDURLRDRURUDUDDRDRRLUDURULDULDDRLDLUURUULUDRLRL"
				+ "RLLLLRLDRURRRUULRDURDRRDDURULLRDUDRLULRRLLLDRLRLRRDULDDUDUURLRULUUUULURULDLDRDRLDD"
				+ "LRLURRUULRRLDULLUULUDUDRLDUDRDLLDULURLUDDUURULDURRUURLRDRRRLDDULLLLDDRRLRRDRDLRUDUUD"
				+ "LRLDRDRURULDLULRRDLLURDLLDLRDRURLRUDURDRRRULURDRURLDRRRDUDUDUDURUUUUULURDUDDRRDULRD"
				+ "DLULRDRULDRUURRURLUDDDDLDRLDLLLLRLDRLRDRRRLLDRDRUULURLDRULLDRRDUUDLURLLDULDUUDLRRRDD"
				+ "UDRLDULRDLLULRRUURRRURLRRLDDUDDLULRUDULDULRDUDRLRDULRUUDDRUURUDLDRDUDDUULLUDDLLRLURU"
				+ "RLRRULLDDDLURDRRDLLLLULLDLUDDLURLLDDRLDLLDDRDRDDUDLDURLUUUUUDLLLRLDULDDRDDDDRUDLULDRR"
				+ "LLLDUUUDDDRDDLLULUULRRULRUDRURDDULURDRRURUULDDDDUULLLURRRRDLDDLRLDDDRLUUDRDDRDDLUDLUUU"
				+ "LLDLRDLURRRLRDRLURUURLULLLLRDDLLLLRUDURRLDURULURULDDRULUDRLDRLLURURRRDURURDRRUDLDDLLRR"
				+ "DRDDLRLRLUDUDRRUDLLDUURUURRDUDLRRLRURUDURDLRRULLDLLUDURUDDRUDULLDUDRRDDUDLLLDLRDRUURLLDL"
				+ "DRDDLDLLUDRDDRUUUDDULRUULRDRUDUURRRURUDLURLRDDLUULRDULRDURLLRDDDRRUDDUDUDLLDDRRUUDURDLLU"
				+ "URDLRULULDULRUURUDRULDRDULLULRRDDLDRDLLLDULRRDDLDRDLLRDDRLUUULUURULRULRUDULRULRUURUDUUDLD"
				+ "UDUUURLLURDDDUDUDLRLULDLDUDUULULLRDUDLDRUDRUULRURDDLDDRDULRLRLRRRRLRULDLLLDDRLUDLULLUUDLD"
				+ "RRLUDULRDRLLRRRULRLRLLUDRUUDUDDLRLDRDDDDRDLDRURULULRUURLRDLLDDRLLRUDRRDDRDUDULRUDULURRUDRD"
				+ "LRDUUDDLDRUDLLDDLRLULLLRUUDRRRRUULLRLLULURLDUDDURLRULULDLDRURDRLLURRDLURRURLULDLRLDUDLULLL"
				+ "DRDLULDLRULLLUDUDUDUDLDDDDDRDLUDUULLUDRLUURDRLULD";
		System.out.println(test145.judgeCircle(string));
	}
	
    public boolean judgeCircle(String moves) {
    	if(moves == null || moves.length() ==0) return true;
        Map<Character, Integer> map = new HashMap<>();
        for(int i=0; i<moves.length(); i++) {
        	Character c = moves.charAt(i);
            if(map.get(c) == null) {
                map.put(c,1);
            } else {
                map.put(c,map.get(c)+1);
            }
        }
        int r = map.get((Character)'R') == null ? 0 : map.get((Character)'R');
        int l = map.get((Character)'L') == null ? 0 : map.get((Character)'L');;
        int u = map.get((Character)'U') == null ? 0 : map.get((Character)'U');;
        int d = map.get((Character)'D') == null ? 0 : map.get((Character)'D');;
        if(r==l && u==d) return true;
        
        return false;                                             
    }
    
    public boolean Nice_judgeCircle(String moves) {
    	char[] move = moves.toCharArray();
    	char[] count = new char[100];  //Nice:
    	
    	for(char c: move) {
    		count[c]++;
    	}
    	return count['U'] ==count['D'] && count['L'] == count['R'];
    }
}
